version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: test-client
    networks:
      - test-net
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    container_name: test-server
    networks:
      - test-net
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    container_name: test-db
    networks:
      - test-net
    volumes:
      - test-data:/data/db

networks:
  test-net:
    driver: bridge

volumes:
  test-data:
    driver: local
