# Загружаем образ Node из Docker Hub
FROM node:14-slim

# Устанавливаем рабочую директорию
WORKDIR /usr/app

# Копируем только package.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Скопируем остальную часть кода в контейнер
COPY . .

# Запускаем на порту 5000
EXPOSE 5000

# Запускаем сервер с помощью nodemon
CMD ["npm", "run", "server"]
